# netlify.toml

[build]
  command = "npm run build"
  publish = "dist" # Carpeta con los archivos estáticos generados

[functions]
  directory = "netlify/functions" # Carpeta con tus funciones sin servidor
